// <auto-generated />
using KendoUIDemo.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace KendoUIDemo.Migrations
{
    [DbContext(typeof(BooksDbContext))]
    [Migration("20181005180306_AddingSeedData")]
    partial class AddingSeedData
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.0-preview2-35157")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("KendoUIDemo.Models.Book", b =>
                {
                    b.Property<int>("BookId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasMaxLength(80);

                    b.Property<int>("NumberOfPages")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValue(0);

                    b.Property<decimal>("Price")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValue(0m);

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200);

                    b.HasKey("BookId");

                    b.ToTable("Book");

                    b.HasData(
                        new
                        {
                            BookId = 1,
                            Author = "Tolstoy",
                            NumberOfPages = 900,
                            Price = 19.95m,
                            Title = "War and Peace"
                        },
                        new
                        {
                            BookId = 2,
                            Author = "Stephenson",
                            NumberOfPages = 550,
                            Price = 9.95m,
                            Title = "Anathem"
                        },
                        new
                        {
                            BookId = 3,
                            Author = "Faulkner",
                            NumberOfPages = 325,
                            Price = 5.50m,
                            Title = "As I Lay Dying"
                        },
                        new
                        {
                            BookId = 4,
                            Author = "Dostoyevsky",
                            NumberOfPages = 700,
                            Price = 18.99m,
                            Title = "Brother K"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
